# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    

    def setupUi(self, Form):
        self.result = 0
        self.temp = 0
        Form.setObjectName("Form")
        Form.resize(608, 800)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 70, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 260, 531, 512))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.b_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_plus.sizePolicy().hasHeightForWidth())
        self.b_plus.setSizePolicy(sizePolicy)
        self.b_plus.setMinimumSize(QtCore.QSize(70, 10))
        self.b_plus.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_plus.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.b_plus.setFont(font)
        self.b_plus.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_plus.setIconSize(QtCore.QSize(0, 0))
        self.b_plus.setObjectName("b_plus")
        self.gridLayout.addWidget(self.b_plus, 2, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.b_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_del.sizePolicy().hasHeightForWidth())
        self.b_del.setSizePolicy(sizePolicy)
        self.b_del.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_del.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.b_del.setFont(font)
        self.b_del.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_del.setIconSize(QtCore.QSize(0, 0))
        self.b_del.setObjectName("b_del")
        self.gridLayout.addWidget(self.b_del, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.b_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_dot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_dot.sizePolicy().hasHeightForWidth())
        self.b_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.b_dot.setFont(font)
        self.b_dot.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_dot.setObjectName("b_dot")
        self.gridLayout.addWidget(self.b_dot, 4, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_0.setAutoDefault(False)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 4, 1, 1, 2)
        self.b_time = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_time.sizePolicy().hasHeightForWidth())
        self.b_time.setSizePolicy(sizePolicy)
        self.b_time.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_time.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.b_time.setFont(font)
        self.b_time.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_time.setIconSize(QtCore.QSize(0, 0))
        self.b_time.setObjectName("b_time")
        self.gridLayout.addWidget(self.b_time, 0, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(70, 10))
        self.pushButton_14.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_14.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_14.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 4, 2, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.b_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_clear.sizePolicy().hasHeightForWidth())
        self.b_clear.setSizePolicy(sizePolicy)
        self.b_clear.setMinimumSize(QtCore.QSize(70, 10))
        self.b_clear.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_clear.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.b_clear.setFont(font)
        self.b_clear.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_clear.setIconSize(QtCore.QSize(0, 0))
        self.b_clear.setObjectName("b_clear")
        self.gridLayout.addWidget(self.b_clear, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 3, 1, 1)
        self.b_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_div.sizePolicy().hasHeightForWidth())
        self.b_div.setSizePolicy(sizePolicy)
        self.b_div.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_div.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.b_div.setFont(font)
        self.b_div.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_div.setIconSize(QtCore.QSize(0, 0))
        self.b_div.setObjectName("b_div")
        self.gridLayout.addWidget(self.b_div, 0, 1, 1, 1)
        self.b_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_minus.sizePolicy().hasHeightForWidth())
        self.b_minus.setSizePolicy(sizePolicy)
        self.b_minus.setMinimumSize(QtCore.QSize(70, 10))
        self.b_minus.setSizeIncrement(QtCore.QSize(0, 0))
        self.b_minus.setBaseSize(QtCore.QSize(0, 47))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.b_minus.setFont(font)
        self.b_minus.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.b_minus.setIconSize(QtCore.QSize(0, 0))
        self.b_minus.setObjectName("b_minus")
        self.gridLayout.addWidget(self.b_minus, 1, 4, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setKerning(True)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgba(90,90,90,1);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(90,90,90,0.8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100,90,80,0.8);\n"
"    border: 2px solid rgba(140,90,80,1);\n"
"    margin-left: 3px;\n"
"    margin-top: 3px;\n"
"    padding-left: 2px;\n"
"    padding-top: 2px;\n"
"}\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 3, 1, 1)
        self.bg = QtWidgets.QGraphicsView(Form)
        self.bg.setGeometry(QtCore.QRect(0, 0, 611, 801))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.bg.setFont(font)
        self.bg.setStyleSheet("QGraphicsView{\n"
"    background-image: url(\'./images/black_bg.png\'); /* Set the image */\n"
"    background-repeat: no-repeat; /* Prevent the image from repeating */\n"
"    background-position: center; /* Center the image in the button */\n"
"    background-size: cover; /* Scale the image to cover the button */\n"
"    color: white;\n"
"}")
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.label.raise_()
        self.gridLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", ""))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.b_plus.setText(_translate("Form", "+"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.b_del.setText(_translate("Form", "Del"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.b_dot.setText(_translate("Form", "."))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.b_time.setText(_translate("Form", "*"))
        self.pushButton_14.setText(_translate("Form", "="))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.b_clear.setText(_translate("Form", "C"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.b_div.setText(_translate("Form", "/"))
        self.b_minus.setText(_translate("Form", "-"))
        self.pushButton_9.setText(_translate("Form", "9"))
    

    def connect_buttons(self):
            self.b_div.clicked.connect(self.division)
            self.b_minus.clicked.connect(self.minus)
            self.b_plus.clicked.connect(self.plus)
            self.b_time.clicked.connect(self.multiply)
            self.b_del.clicked.connect(self.delete)
            self.b_clear.clicked.connect(self.clear)
            self.b_dot.clicked.connect(self.dot)
            self.pushButton_14.clicked.connect(self.calculate)
            self.pushButton_0.clicked.connect(self.zero)
            self.pushButton_1.clicked.connect(self.one)
            self.pushButton_2.clicked.connect(self.two)
            self.pushButton_3.clicked.connect(self.three)
            self.pushButton_4.clicked.connect(self.four)
            self.pushButton_5.clicked.connect(self.five)
            self.pushButton_6.clicked.connect(self.six)
            self.pushButton_7.clicked.connect(self.seven)
            self.pushButton_8.clicked.connect(self.eight)
            self.pushButton_9.clicked.connect(self.nine)

    def division(self):
        self.label.setText(self.label.text() + "/")

    def minus(self):
        self.label.setText(self.label.text() + "-")

    def plus(self):
        self.label.setText(self.label.text() + "+")

    def multiply(self):
        self.label.setText(self.label.text() + "*")

    def delete(self):
        self.label.setText(self.label.text()[:-1])

    def clear(self):
        self.label.setText("")
        self.temp = 0

    def dot(self):
        self.label.setText(self.label.text() + ".")


    # this main methods calculation
    def calculate(self):
        try:
            if "=" in self.label.text():
                self.label.setText(str(self.result))
                self.temp = 0
            else:
                # if self.temp == 0 :
                result = eval(self.label.text())
                self.label.setText(self.label.text() + " = " + str(result))
                self.result = result
                self.temp = 1

        except Exception as e:
            self.label.setText("Error")

    #===========================================================

    def zero(self):
        self.label.setText(self.label.text() + "0")

    def one(self):
        self.label.setText(self.label.text() + "1")

    def two(self):
        self.label.setText(self.label.text() + "2")

    def three(self):
        self.label.setText(self.label.text() + "3")

    def four(self):
        self.label.setText(self.label.text() + "4")

    def five(self):
        self.label.setText(self.label.text() + "5")

    def six(self):
        self.label.setText(self.label.text() + "6")

    def seven(self):
        self.label.setText(self.label.text() + "7")

    def eight(self):
        self.label.setText(self.label.text() + "8")

    def nine(self):
        self.label.setText(self.label.text() + "9")

class Calculator(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.connect_buttons()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = Calculator()
    calculator.show()
    sys.exit(app.exec_())